### ISSUE TITLE
[4.16.0] NDI third party libraries missing when packaging for linux

### ISSUE THREAD

**Issue by GundlackFlorian** [ue4plugins/NdiMedia#16]
Hi,
Just tried today to launch the packaged linux build and it comes out that the "Third Party" folder with the librairies is not packaged with it.
On windows the files are copied and the plugin works fine.

After copying the files by hand it works.
I tried to add the path to the files/folder into a /Config/FilterPlugin.ini file but changed nothing.

PS: i have also a crash issue at runtime, but i will first investigate to be sure it comes from the plugin before opening an other issue.

**Comment by gmpreussner** [comment]
Thanks gundz, can you try the fix I just checked in?

Also, do you have a callstack for the crash? I can take a look at that as well. There is a known shutdown crash on Windows that I couldn't figure out yet. It only happens when the game or Editor is exited, and something inside NDI is dereferencing an invalid pointer. It's possible that the same thing happens on other platforms - I haven't tried.

I don't know of any runtime crashes in NdiMedia at this time, but that doesn't mean there aren't any :)

**Comment by GundlackFlorian** [comment]
Your fix works perfectly !

For the other issue i'll check more in details tomorow and open another issue if its relevant (the crash happens in the NDIlib_find_get_current_sources function, the same (if i remember well the same line as the windows crash that happens sometimes)

Thanks for your quick answer !
