### ISSUE TITLE
NDILIB_LIBRARY_NAME wrong for linux

### ISSUE THREAD

**Issue by GundlackFlorian** [ue4plugins/NdiMedia#25]
Hi !

There is a small typo issue with the `NDILIB_LIBRARY_NAME` define in the `Processing.NDI.Lib.h` file (line 59):

it should be `"libndi.so.3.0.11"` instead of `"libndi.so.3.11"`, overwise we got a "LogNdiMedia: Error: Failed to initialize NDI"

**Comment by gmpreussner** [comment]
I removed the NDI SDK files from the plug-in. They are now required to be installed via the official NDI SDK installer. As a result, the NDI SDK version has also been downgraded from 3.5 Preview to 3.0. The typo in the SDK headers should be fixed with the release of the official 3.5 SDK later this week.
